// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDYiGQObyO7Z6bIWzCsbWXbS5GBqSMeo',
    appId: '1:1091845409879:web:9a8de4ed1b268f6ac3a712',
    messagingSenderId: '1091845409879',
    projectId: 'bookmanagement-firebase-e5642',
    authDomain: 'bookmanagement-firebase-e5642.firebaseapp.com',
    storageBucket: 'bookmanagement-firebase-e5642.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqzLTLnVeMhOydVfcU_Z2BG2Kp1z1mPo',
    appId: '1:1091845409879:android:b1d97a53bb335127c3a712',
    messagingSenderId: '1091845409879',
    projectId: 'bookmanagement-firebase-e5642',
    storageBucket: 'bookmanagement-firebase-e5642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTlXlVUjSBdViMDHLPoA-qTpRUl5DhxVI',
    appId: '1:1091845409879:ios:4fe23b7594304e9cc3a712',
    messagingSenderId: '1091845409879',
    projectId: 'bookmanagement-firebase-e5642',
    storageBucket: 'bookmanagement-firebase-e5642.firebasestorage.app',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTlXlVUjSBdViMDHLPoA-qTpRUl5DhxVI',
    appId: '1:1091845409879:ios:4fe23b7594304e9cc3a712',
    messagingSenderId: '1091845409879',
    projectId: 'bookmanagement-firebase-e5642',
    storageBucket: 'bookmanagement-firebase-e5642.firebasestorage.app',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxDYiGQObyO7Z6bIWzCsbWXbS5GBqSMeo',
    appId: '1:1091845409879:web:e1cde2404874863bc3a712',
    messagingSenderId: '1091845409879',
    projectId: 'bookmanagement-firebase-e5642',
    authDomain: 'bookmanagement-firebase-e5642.firebaseapp.com',
    storageBucket: 'bookmanagement-firebase-e5642.firebasestorage.app',
  );
}
